bytedance/mockey

- mock_var.go
- mock_var_test.go
Change-Id: I2b1c58ccb694bb00d468caf16b839be558fa7276
fix: unPatch panic when MockValue on nil interface
en: fix bug unPatching panic when using MockValue to mock a interface variable
zh: 修复MockVar对象是nil时，reflect.Value无法直接reset导致unPatch失败的问题
[reflect: call of reflect.Value.Set on zero Value](https://github.com/bytedance/mockey/issues/4)
> fix: unPatch panic when MockValue on nil interface

- convey.go
- internal/tool/caller.go
- mock.go
- mock_var.go
- tests/remock_test.go
refactor: add previous mock line into re-mock panic information
en: add previous mock line into re-mock panic information. So users can fast-locate where target last mocked
zh: 当发生re-mock错误时在panic信息里添加最近一次mock的代码位置，以便使用者快速定位
> refactor: add previous mock line into re-mock panic information

- internal/monkey/common/mem_above_1_19.go
- internal/monkey/common/mem_below_1_19.go
- internal/monkey/common/page_test.go
Fix bug: misusage of runtime.sysAlloc may lead to runtime failure in Go 1.19
en: fix AllocatePage bug that may cause runtime crash in Go 1.19+ 
zh: 修复AllocatePage因为传入的sysStat无法进入runtime的MemStats统计从而riuntime获取内存统计时整个运行时崩溃的问题
Fixes https://github.com/bytedance/mockey/issues/13
> fix: misusage of runtime.sysAlloc may lead to runtime failure in Go 1.19

- utils.go
- utils_test.go
fix panic when `GetMethod` on nested interface
fix
en: fix panic when `GetMethod` on nested interface
zh: 修复在获取嵌套interface的结构体方法时可能的零值问题
#19
> fix: Panic when GetMethod on nested interface

- mock.go
- mock_test.go
- utils_test.go
see https://github.com/bytedance/mockey/issues/15
Change-Id: I1949762b22f78e9b84d9dec8771387f2994e94d4
fix
en: fix bugs when using `Origin` on struct method  [https://github.com/bytedance/mockey/issues/15](url)
zh: 修复对struct方法进行`Origin`时会报错的问题
https://github.com/bytedance/mockey/issues/15
> fix: Origin(&ori) NOT works properly with struct methods

- mock_condition.go
- mock_sequence.go
- mock_sequence_test.go
- private.go
Change-Id: I95036796bdffd559cb713ec3485fa6f064eaf1fa
feat: Support sequence returns with one single `Return`
en: Support sequence returns with one single `Return`
zh: 支持在一个return里序列化设置顺序返回值
> feat: support sequence return

- mock.go
docs
en: add documentation for To and When
zh: 添加To和When的使用文档
Fixes #5
> doc: add documentation for To and When

- .github/workflows/tests.yml
- go.mod
- internal/monkey/inst/disasm_amd64.go
- internal/monkey/inst/disasm_arm64.go
- internal/monkey/patch.go
- mock.go
- mock_generics.go
- mock_generics_test.go
- option.go
suport generics mocking (need go1.18+)
feat
en:  support generics like `func sum[T int|float](_,_ T) T` 
zh: 支持泛型mock
> feat: suport generics mocking (need go1.18+)

- mock.go
- mock_generics.go
- mock_generics_test.go
- option.go
Change-Id: Ie50943a941eefd595f705154454e769449e7ac2f
en: 
zh:
> refactor: rename OptionUnsafe&OptionGeneric to OptXxx

- internal/tool/call.go
Change-Id: Ic9ac689e33484828b27adeca2d342e87c4230362
fix
en:  There are a few cases that `lastArgs.cap == 0` but `lastArg.len == MAX_INT` when calling variadic functions (arm64). Currently we have no idea how it happens. In that case we assume that `lastArgs.len` should less than `lastArg.cap`
zh: 在一些极少情况下mock可变长参数的函数，调用时最后的变长参数slice的len会变得很大，但是cap为0。目前还不清楚为什么slice的len被踩坏了，这里先做一个校验，如果len>cap的话按照cap长度调用mock函数
> fix: check variadic function's cap before calling

- internal/monkey/inst/inst_arm64.go
- mock_test.go
Change-Id: Ieb6ca78a9efbe523a9595500845e2c61884e58c3
fix
en: use x19 register(arm64) for BR instruction
zh: arm下使用x19寄存器传参，避免入参值被踩坏
> fix: use x19 register(arm64) for BR instruction

- .github/workflows/tests.yml
- internal/monkey/common/runtime_above_1_21.go
- internal/monkey/common/runtime_below_1_21.go
Change-Id: I2140c815e893f2f44684f73d8e8cdf46eeb773b1
feat: support go1.21
en: support go1.21
zh: 支持go1.21
> feat: support go1.21

- internal/tool/check_gcflags.go
Change-Id: I34505cea2eb96cddff5b7da71f918ca2d21c134d
fix
en: do not panic when user forget to add gcflags
zh: 检查gcflags失败的情况不panic，改为打err日志
> fix: do not panic when user forget to add gcflags

- README_cn.md
en: modified sick sentences
zh: 修改病句
> docs: update readme —— modified sick sentences

- exp/utils_above_1_18.go
- exp/utils_above_1_18_test.go
- internal/unsafereflect/name_above_1_17.go
- internal/unsafereflect/name_below_1_17.go
- internal/unsafereflect/type.go
- internal/unsafereflect/type_above_1_17_test.go
- internal/unsafereflect/type_test.go
feat: A new feature
en: 1. We need to mock some method even if it's not exported, like `(*sha256.digest).checksum` or other method; 2. We need some helper function to migrate `gomonkey.ApplyPrivateMethod`.
zh: 1. 某些场景下我们需要Mock私有方法，比如`(*sha256.digest).checksum`；2. 我们需要一个辅助函数去实现从`gomonkey.ApplyPrivateMethod`的代码实现迁移。
> feat: support get private member method

- internal/monkey/fn/copy_darwin.go
- internal/monkey/patch.go
- internal/tool/call.go
- internal/tool/check.go
- mock.go
- mock_condition.go
- mock_generics.go
- mock_generics_test.go
fix
en: fix bug that 'When/To' hook's input value be all incorrect when mock generic functions 
zh: 修复在mock泛型函数时使用When/To，目标函数的入参值会全部变错误的问题
> fix: wrong parameter value when using To/When on generic functions

- internal/monkey/mem/write.go
- internal/monkey/mem/write_test.go
Change-Id: I65f95f8be6c7f77f903efde5877d42856473c306
fix
en: Change page write to one by one to avoid cross-page writing failure
zh: 写page时改成一个一个写，避免跨page写入时因权限问题导致的调用失败
> fix: panic when write code cross-page

- .github/workflows/tests.yml
- internal/monkey/inst/disasm_amd64.go
- internal/monkey/inst/disasm_arm64.go
- internal/monkey/inst/generic_extra.go
- internal/monkey/inst/generic_extra_race.go
- mock.go
Change-Id: I96e199d96a1a801ad37ad31d81f0b544cd8c0f9e
fix
en: Support `-race` for generic function mocks
zh: 泛型mock支持单测`-race`参数
> fix: support -race for generic function mocks

- README.md
- README_cn.md
en:  add go 1.23 build error FAQ
zh: 增加FAQ解决1.23编译问题
> add more faq for go 1.23

- go.mod
- go.sum
- internal/monkey/common/page_alloc.go
- internal/monkey/common/page_alloc_windows.go
- internal/monkey/mem/write_darwin_linux_test.go
- internal/monkey/mem/write_test.go
Change-Id: I48df2c97f43e74b164fc724ee572a8aa0b691473
fix
en: Fix the bug of failed memory allocation during compilation under Windows
zh: 修复windows下内存分配编译不通过的问题
https://github.com/bytedance/mockey/issues/62
> fix: memory allocate in windows

- README.md
docs: Documentation only changes
en: Improved the English documentation. 
Most of the examples are taken and clarified from the internal Bytedance documentation
Sorry I can't help with the Chinese version :(
Fixes #67 
I am a bytedance employee 🥳
> Improved English documentation
